{
 "title": "Wiki App Dashboard",
 "tags": [
  "flask",
  "wiki",
  "monitoring"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests (rate)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(request_count_created[5m])",
     "legendFormat": "HTTP Requests Rate"
    }
   ]
  },
  {
   "title": "CPU Usage (seconds)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "CPU Seconds"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory" }
   ]
  }
 ]
}