apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki-app
  template:
    metadata:
      labels:
        app: wiki-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: wiki-app
        image: severali/wiki-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
