apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki-app
  template:
    metadata:
      labels:
        app: wiki-app
    spec:
      containers:
      - name: wiki-app
        image: severali/wiki-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
