apiVersion: v1
kind: Service
metadata:
  name: wiki-app-service
  labels:
    app: wiki-app
spec:
  type: LoadBalancer
  selector:
    app: wiki-app
  ports:
    - name: http    
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500     